"""
Automated academic report generation (HTML with embedded figures).

Usage::
    gen = ReportGenerator(output_dir="reports/")
    gen.single_dyad_report(results, filepath="dyad.html")
    gen.group_report(comparison, filepath="group.html")

Requires: ``pip install matplotlib`` (optional, degrades gracefully).
"""

from __future__ import annotations

import base64
import io
import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np

# Matplotlib is optional — report module degrades gracefully
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches
    _MPL_AVAILABLE = True
except ImportError:
    _MPL_AVAILABLE = False

from .core import AnalysisResults
from .__about__ import __version__


# ---------------------------------------------------------------------------
# Stylesheet (APA-style, minimal)
# ---------------------------------------------------------------------------

_CSS = """
body {
  font-family: "Times New Roman", Times, serif;
  font-size: 12pt;
  line-height: 1.6;
  max-width: 960px;
  margin: 40px auto;
  color: #1a1a1a;
  background: #fff;
}
h1 { font-size: 18pt; font-weight: bold; text-align: center; margin-bottom: 4px; }
h2 { font-size: 14pt; font-weight: bold; border-bottom: 1px solid #ccc;
     padding-bottom: 4px; margin-top: 36px; }
h3 { font-size: 12pt; font-weight: bold; margin-top: 20px; }
table { border-collapse: collapse; width: 100%; font-size: 11pt; margin: 16px 0; }
th { border-bottom: 2px solid #333; padding: 6px 12px; text-align: left; }
td { border-bottom: 1px solid #ddd; padding: 4px 12px; }
tr:last-child td { border-bottom: 2px solid #333; }
.sig { font-weight: bold; color: #005500; }
.warning { color: #884400; font-size: 10pt; }
.footer {
  margin-top: 60px; padding-top: 12px;
  border-top: 1px solid #ccc;
  font-size: 9pt; color: #666; text-align: center;
}
.figure { text-align: center; margin: 20px 0; }
.figure img { max-width: 100%; }
.figure p { font-size: 10pt; color: #444; margin-top: 4px; }
.dyad-section { page-break-inside: avoid; }
.badge {
  display: inline-block; background: #1D9E75; color: white;
  padding: 2px 8px; border-radius: 3px; font-size: 9pt;
  font-family: sans-serif; letter-spacing: 0.5px;
}
"""

_FOOTER_TEMPLATE = """
<div class="footer">
  Generated by <span class="badge">SyncPipe v{version}</span> &nbsp;|&nbsp;
  Dynamic process analysis for interpersonal synchrony research &nbsp;|&nbsp;
  {timestamp} &nbsp;|&nbsp;
  <em>If you use this analysis in a publication, please cite SyncPipe
  (github.com/EriXPsy/multisync).</em>
</div>
"""


# ---------------------------------------------------------------------------
# Figure helpers
# ---------------------------------------------------------------------------

def _fig_to_base64(fig) -> str:
    """Encode a matplotlib figure as a base64 PNG string."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight")
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode("ascii")
    plt.close(fig)
    return f'<img src="data:image/png;base64,{b64}" alt="figure"/>'


def _plot_group_comparison(test_results: List[Any], label_a: str, label_b: str) -> str:
    """Bar chart comparing means across groups."""
    if not _MPL_AVAILABLE or not test_results:
        return "<p class='warning'>No test results — figure skipped.</p>"

    sig = [r for r in test_results if r.significant_fdr]
    all_r = sig if sig else test_results[:8]

    metrics = [r.metric.replace("_", " ").capitalize() for r in all_r]
    means_a = [r.mean_a for r in all_r]
    means_b = [r.mean_b for r in all_r]

    x = np.arange(len(metrics))
    width = 0.35

    fig, ax = plt.subplots(figsize=(max(5, len(metrics) * 1.5), 4))
    bars_a = ax.bar(x - width/2, means_a, width, label=label_a,
                    color="#378ADD", edgecolor="#333", linewidth=0.5)
    bars_b = ax.bar(x + width/2, means_b, width, label=label_b,
                    color="#D85A30", edgecolor="#333", linewidth=0.5)

    ax.set_xticks(x)
    ax.set_xticklabels(metrics, rotation=30, ha="right", fontsize=9)
    ax.set_ylabel("Mean value", fontsize=10)
    ax.set_title(
        f"Group comparison: {label_a} vs {label_b}\n"
        + ("(significant metrics only)" if sig else "(all metrics)"),
        fontsize=11,
    )
    ax.legend(fontsize=9)

    # Significance stars
    for i, r in enumerate(all_r):
        if r.significant_fdr:
            max_val = max(r.mean_a, r.mean_b)
            ax.text(i, max_val * 1.05, "*", ha="center", fontsize=12,
                    color="#005500")

    fig.tight_layout()
    return _fig_to_base64(fig)


# ---------------------------------------------------------------------------
# HTML building helpers
# ---------------------------------------------------------------------------

def _html_table(rows: List[Dict[str, Any]], highlight_key: Optional[str] = None,
                highlight_val: Any = True) -> str:
    if not rows:
        return "<p>No data.</p>"
    keys = list(rows[0].keys())
    header = "<tr>" + "".join(f"<th>{k}</th>" for k in keys) + "</tr>"
    body = ""
    for row in rows:
        row_class = ""
        if highlight_key and row.get(highlight_key) == highlight_val:
            row_class = ' class="sig"'
        cells = ""
        for k in keys:
            v = row[k]
            if isinstance(v, float):
                cells += f"<td>{v:.4f}</td>" if not np.isnan(v) else "<td>—</td>"
            elif isinstance(v, bool):
                cells += f"<td>{'✓' if v else ''}</td>"
            else:
                cells += f"<td>{v}</td>"
        body += f"<tr{row_class}>{cells}</tr>"
    return f"<table><thead>{header}</thead><tbody>{body}</tbody></table>"


def _html_wrap(title: str, body: str, version: str) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    footer = _FOOTER_TEMPLATE.format(version=version, timestamp=ts)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>{title} — SyncPipe Report</title>
<style>{_CSS}</style>
</head>
<body>
{body}
{footer}
</body>
</html>"""


# ---------------------------------------------------------------------------
# ReportGenerator
# ---------------------------------------------------------------------------

class ReportGenerator:
    """
    Generate publication-ready HTML reports from SyncPipe results.

    Parameters
    ----------
    output_dir : str
        Default output directory for reports.
    """

    def __init__(self, output_dir: str = "reports/") -> None:
        self.output_dir = Path(output_dir)

    def single_dyad_report(
        self,
        results: AnalysisResults,
        filepath: Optional[str] = None,
        title: Optional[str] = None,
    ) -> str:
        """
        Generate a single-dyad analysis report.

        Parameters: results (AnalysisResults), filepath, title.
        Returns: path to written HTML file.
        """
        if filepath is None:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            filepath = str(self.output_dir / f"{results.dyad_id}_report.html")

        title = title or f"Synchrony Analysis Report — {results.dyad_id}"
        body = f"<h1>{title}</h1>\n"
        body += f"<p style='text-align:center;color:#666'>Dyad ID: <code>{results.dyad_id}</code></p>\n"

        # --- Parameters ---
        body += "<h2>Analysis parameters</h2>\n"
        params = results.parameters or {}
        param_rows = [{"Parameter": k, "Value": str(v)} for k, v in params.items()]
        body += _html_table(param_rows)

        # --- Dynamic Features ---
        body += "<h2>Dynamic synchrony features</h2>\n"
        feat = results.dynamic_features
        if feat:
            feat_rows = []
            for pair_key, pair_feats in feat.items():
                for feat_name, val in pair_feats.items():
                    if val is not None and not (isinstance(val, float) and np.isnan(val)):
                        feat_rows.append({
                            "Pair": pair_key,
                            "Feature": feat_name.replace("_", " ").capitalize(),
                            "Value": round(float(val), 4) if isinstance(val, (float, int)) else val,
                        })
            body += _html_table(feat_rows[:40])
        else:
            body += "<p>No dynamic features computed.</p>\n"

        # --- Prediction ---
        body += "<h2>Prediction window analysis</h2>\n"
        pred = results.prediction
        if pred:
            pred_rows = [{
                "Pair": k,
                "Mean Dynamic AUC": round(float(v.get("mean_dynamic_auc", float("nan"))), 4),
                "Mean Baseline AUC": round(float(v.get("mean_baseline_auc", float("nan"))), 4),
                "ΔAUC": round(float(v.get("mean_delta_auc", float("nan"))), 4),
                "Warning": v.get("warning") or "",
            } for k, v in pred.items()]
            body += _html_table(pred_rows)
            body += "<p class='warning'>ΔAUC &gt; 0: dynamic features outperform AR baseline. "
            body += "Bootstrap 95% CI is underestimated when folds &lt; 10.</p>\n"

        # --- Diagnostics ---
        body += "<h2>Pipeline diagnostics</h2>\n"
        diags = results.diagnostics
        if diags:
            diag_rows = [{
                "Stage": d.get("stage", "?"),
                "Pair": d.get("pair", "?"),
                "Reason": d.get("reason", "?"),
            } for d in diags]
            body += f"<p class='warning'>{len(diags)} event(s) flagged by the pipeline.</p>\n"
            body += _html_table(diag_rows)
        else:
            body += "<p>No pipeline warnings.</p>\n"

        # Write file
        html = _html_wrap(title, body, __version__)
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(html, encoding="utf-8")
        return str(path)

    def group_report(
        self,
        comparison: Any,  # GroupComparisonReport
        filepath: Optional[str] = None,
        title: Optional[str] = None,
    ) -> str:
        """
        Generate a group-level comparison report.

        Parameters: comparison (GroupComparisonReport), filepath, title.
        Returns: path to written HTML file.
        """
        if filepath is None:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            filepath = str(self.output_dir / "group_comparison_report.html")

        la, lb = comparison.label_a, comparison.label_b
        title = title or f"Group Comparison: {la} vs {lb}"
        body = f"<h1>{title}</h1>\n"
        body += (f"<p style='text-align:center;color:#666'>"
                 f"{la} (n={comparison.n_a}) vs {lb} (n={comparison.n_b}) | "
                 f"α={comparison.alpha} | FDR: Benjamini-Hochberg</p>\n")

        # --- Overview figure ---
        body += "<h2>Group comparison overview</h2>\n"
        body += "<div class='figure'>"
        body += _plot_group_comparison(comparison.test_results, la, lb)
        body += "</div>\n"
        body += "<p class='warning'>* = significant after FDR correction.</p>\n"

        # --- Full statistics table ---
        body += "<h2>Full statistical results</h2>\n"
        stat_rows = [{
            "Metric": r.metric.replace("_", " ").capitalize(),
            f"Mean {la}": round(r.mean_a, 4),
            f"Mean {lb}": round(r.mean_b, 4),
            "Effect size": round(r.effect_size, 4) if not np.isnan(r.effect_size) else "—",
            "Test": r.test_name,
            "p (raw)": round(r.p_raw, 4) if not np.isnan(r.p_raw) else "—",
            "p (FDR)": round(r.p_fdr, 4) if not np.isnan(r.p_fdr) else "—",
            "Sig *": "✓" if r.significant_fdr else "",
        } for r in sorted(comparison.test_results, key=lambda x: x.p_raw if not np.isnan(x.p_raw) else 1.0)]
        body += _html_table(stat_rows)

        # --- Per-dyad table (Group A) ---
        body += f"<h2>Individual dyad results — {la}</h2>\n"
        dyad_rows_a = [dr.to_dict() for dr in comparison.dyad_results_a]
        body += _html_table(dyad_rows_a)

        # --- Per-dyad table (Group B) ---
        body += f"<h2>Individual dyad results — {lb}</h2>\n"
        dyad_rows_b = [dr.to_dict() for dr in comparison.dyad_results_b]
        body += _html_table(dyad_rows_b)

        # Write
        html = _html_wrap(title, body, __version__)
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(html, encoding="utf-8")
        return str(path)
