"""Migration: add _defined flags to Lerique per_record_features.csv.

Reads the existing per_record_features.csv (generated by
run_lerique_pilot.py BEFORE the NaN-semantics fix in
feature_definitions.py) and applies:

  1. onset_latency  NaN → wcc_window_sec  + onset_defined=0
  2. rise_time      NaN → wcc_window_sec  + rise_defined=0
  3. recovery_time  NaN → wcc_window_sec  + recovery_defined=0

Existing non-NaN values are left untouched with _defined=1.

The output CSV matches what a re-run of run_lerique_pilot.py with the
fixed feature_definitions.py would produce.

Usage:
    python scripts/migrate_lerique_defined_flags.py [--wcc-window-sec 30]
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
CSV_IN = REPO_ROOT / "artifacts" / "realtest" / "lerique_2024" / "per_record_features.csv"
CSV_OUT = CSV_IN  # overwrite in-place by default
# Backup will be saved as per_record_features_pre_migration.csv
CSV_BACKUP = CSV_IN.with_name("per_record_features_pre_migration.csv")


def migrate(wcc_window_sec: float = 30.0) -> None:
    df = pd.read_csv(CSV_IN)
    n_before = len(df)

    # ── Backup ──
    if CSV_OUT == CSV_IN and not CSV_BACKUP.exists():
        df.to_csv(CSV_BACKUP, index=False)
        print(f"Backup saved: {CSV_BACKUP}")

    # ── onset_latency ──
    if "onset_defined" not in df.columns:
        onset_nan = df["onset_latency"].isna()
        df["onset_defined"] = (~onset_nan).astype(int)
        df.loc[onset_nan, "onset_latency"] = float(wcc_window_sec)
        print(f"onset_latency: {int(onset_nan.sum())} NaN → {wcc_window_sec}s "
              f"(onset_defined=0); {int((~onset_nan).sum())} defined")

    # ── rise_time ──
    if "rise_defined" not in df.columns:
        rise_nan = df["rise_time"].isna()
        df["rise_defined"] = (~rise_nan).astype(int)
        df.loc[rise_nan, "rise_time"] = float(wcc_window_sec)
        print(f"rise_time:     {int(rise_nan.sum())} NaN → {wcc_window_sec}s "
              f"(rise_defined=0); {int((~rise_nan).sum())} defined")

    # ── recovery_time ──
    if "recovery_defined" not in df.columns:
        rec_nan = df["recovery_time"].isna()
        df["recovery_defined"] = (~rec_nan).astype(int)
        df.loc[rec_nan, "recovery_time"] = float(wcc_window_sec)
        print(f"recovery_time: {int(rec_nan.sum())} NaN → {wcc_window_sec}s "
              f"(recovery_defined=0); {int((~rec_nan).sum())} defined")

    # ── Verify no leftover NaN ──
    for col in ["onset_latency", "rise_time", "recovery_time"]:
        if df[col].isna().any():
            print(f"WARNING: {col} still has NaN after migration!")

    df.to_csv(CSV_OUT, index=False)
    print(f"\nMigrated {n_before} rows → {CSV_OUT}")
    print(f"New columns: {[c for c in df.columns if c.endswith('_defined')]}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Add _defined flags to Lerique features CSV")
    parser.add_argument(
        "--wcc-window-sec", type=float, default=30.0,
        help="WCC window duration in seconds (fill value for undefined; default 30)",
    )
    args = parser.parse_args()
    migrate(wcc_window_sec=args.wcc_window_sec)


if __name__ == "__main__":
    main()
