"""
B4 — FDR-family bake-off + leave-one-dyad-out (LOO) stability test.

Purpose
-------
Produce *evidence* for the SyncPipe v1 primary-FDR-family membership decision:
which WCC-derived features may be treated as independent tests (low collinearity)
vs. which should stay exploratory/reference.

For each of the three real datasets (Lerique 2024 / Gordon / Andersen) we:
  1. Build a per-DYAD feature matrix (rows = independent dyads).
  2. Compute the Pearson-rho matrix + Variance Inflation Factor (VIF) per feature.
  3. Leave-one-dyad-out (LOO): drop one dyad, recompute the VIF-qualifying set
     (feature qualifies for the FDR family iff VIF < VIF_SEVERE), and count how
     often the membership decision *changes*. Report per-feature and overall
     stability %.

Data-availability gate (B1)
---------------------------
  * Lerique: the in-repo derived feature table
    ``artifacts/realtest/lerique_2024/per_record_features.csv`` is present
    -> REAL bake-off (dyad-level aggregation of shipped real features).
  * Gordon / Andersen: the real source CSVs are NOT in the repo (OSF is
    "No license"; the user downloads them externally — see docs/DATA_ACCESS.md,
    B1 blocker). When absent we fall back to a SYNTHETIC pipeline smoke test
    using ``multisync.synthetic.generate_ground_truth_dyad`` -> real WCC +
    feature extraction on synthetic dyads. Synthetic numbers are clearly
    labelled (mode="synthetic") and are NOT used as evidence for the
    FDR-family decision; they only prove the script/pipeline runs end-to-end.

This script does NOT modify any source constants (T_def / n_min are B3).

Outputs
-------
  artifacts/bakeoff/fdr_family_bakeoff.csv        (wide: rows=features/pairs, cols=datasets)
  artifacts/bakeoff/fdr_family_loo_stability.csv  (per-feature LOO stability)

Run from repo root:
    python scripts/bakeoff_fdr_family.py
"""
from __future__ import annotations

import json
import sys
import warnings
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

# ── repo path ────────────────────────────────────────────────────────────────
REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from multisync.feature_vif_test import (  # noqa: E402
    feature_vif,
    VIF_CONCERN,
    VIF_SEVERE,
)
from multisync.synthetic import generate_ground_truth_dyad  # noqa: E402
from multisync.dynamic_features import sliding_window_wcc, extract_dynamic_features  # noqa: E402

# ── constants ─────────────────────────────────────────────────────────────────
# Canonical candidate feature set for the FDR-family bake-off.
FDR_CANDIDATES: List[str] = [
    "mean_synchrony",
    "peak_amplitude",
    "dwell_time",
    "switching_rate",
    "bimodality_coefficient",
    "synchrony_entropy",
    "onset_latency",
    "rise_time",
    "recovery_time",
]
# v1 primary FDR family (frozen in docs/DECISION_LOG.md) — reference for reporting.
FDR_PRIMARY = {"peak_amplitude", "dwell_time", "switching_rate"}
FDR_REFERENCE = {"mean_synchrony"}

LEROIQUE_CSV = (
    REPO / "artifacts" / "realtest" / "lerique_2024" / "per_record_features.csv"
)
OUT_DIR = REPO / "artifacts" / "bakeoff"

# Synthetic mirror sample sizes (match real n_records: Lerique 68, Gordon 48,
# Andersen 24) so the synthetic smoke exercises the same LOO scale.
SYNTH_N = {"gordon": 48, "andersen": 24}
SYNTH_SEED = {"gordon": 20240701, "andersen": 20240702}

WCC_WIN = 30          # samples at 1 Hz (matches export_wcc_vif_morphology.py)
LOO_MIN_N = 23        # task: LOO only for datasets with N >= 23 dyads


# ═══════════════════════════════════════════════════════════════════════════
# Data loading
# ═══════════════════════════════════════════════════════════════════════════
def load_lerique_real() -> Tuple[pd.DataFrame, List[str], str]:
    """Return (feature_df, dyad_keys, mode). Rows = per-record (matches the
    prior artifacts/vif convention); dyad_keys let us do true leave-one-DYAD-out."""
    df = pd.read_csv(LEROIQUE_CSV)
    feats = [c for c in FDR_CANDIDATES if c in df.columns]
    df = df[["dyad_label"] + feats].copy()
    dyad_keys = df["dyad_label"].astype(str).tolist()
    return df, dyad_keys, "real"


def generate_synthetic_dataset(name: str, n_dyads: int, seed: int) -> Tuple[pd.DataFrame, List[str], str]:
    """Synthetic pipeline smoke: real WCC + feature extraction on synthetic
    dyads generated by ``generate_ground_truth_dyad``. Returns per-dyad rows."""
    rng_master = np.random.default_rng(seed)
    rows: List[Dict[str, float]] = []
    dyad_keys: List[str] = []
    for i in range(n_dyads):
        # Vary coupling / lag / burst structure across dyads so features vary
        # (zero variance would make VIF undefined).
        coupling = float(rng_master.uniform(0.35, 0.9))
        lag = float(rng_master.choice([0.0, 6.0, 12.0]))
        n_bursts = int(rng_master.integers(3, 8))
        noise = float(rng_master.uniform(0.15, 0.4))
        ds = generate_ground_truth_dyad(
            lead_modality="behavior",
            lag_modality="behavior",
            true_lag_sec=lag,
            noise_ratio=noise,
            duration_sec=300.0,
            hz=1.0,
            seed=int(rng_master.integers(1, 1_000_000)),
            n_bursts=n_bursts,
            burst_sigma=3.0,
            gap_prob=0.0,
            morphology="identical",
            coupling=coupling,
        )
        a = ds.get_aligned_array("behavior", "person_a")
        b = ds.get_aligned_array("behavior", "person_b")
        a = np.asarray(a, dtype=float)
        b = np.asarray(b, dtype=float)
        n = min(a.size, b.size)
        if n < WCC_WIN + 5:
            continue
        wcc = sliding_window_wcc(a[:n], b[:n], window_size=WCC_WIN, hz=1.0)
        if wcc.size < 5 or not np.isfinite(wcc).any():
            continue
        feats = extract_dynamic_features(wcc, hz=1.0, wcc_window_sec=float(WCC_WIN))
        rec = {f: float(getattr(feats, f, np.nan)) for f in FDR_CANDIDATES}
        rows.append(rec)
        dyad_keys.append(f"{name}_syn_{i:03d}")
    df = pd.DataFrame(rows)
    return df, dyad_keys, "synthetic"


# ═══════════════════════════════════════════════════════════════════════════
# Analysis
# ═══════════════════════════════════════════════════════════════════════════
def pearson_rho(df: pd.DataFrame, feats: List[str]) -> pd.DataFrame:
    return df[feats].apply(pd.to_numeric, errors="coerce").corr(method="pearson")


def loo_stability(df: pd.DataFrame, dyad_keys: List[str], feats: List[str]) -> Dict[str, object]:
    """Leave-one-dyad-out VIF-qualifying-set stability.

    A feature *qualifies* for the primary FDR family iff its VIF < VIF_SEVERE.
    We count, over all dyad removals, how often each feature flips its
    qualify status and how often the overall qualifying *set* changes.
    """
    unique_dyads = list(dict.fromkeys(dyad_keys))
    n = len(unique_dyads)
    full_vif = feature_vif(df, feats)
    full_qual = {f: (bool(full_vif.get(f, np.nan) < VIF_SEVERE)) for f in feats}
    full_set = frozenset(f for f, ok in full_qual.items() if ok)

    flips = {f: 0 for f in feats}
    set_changes = 0
    for d in unique_dyads:
        mask = np.array([k != d for k in dyad_keys], dtype=bool)
        sub = df.loc[mask]
        if sub.shape[0] < LOO_MIN_N:
            # not enough left to re-estimate; skip this fold (counts as neutral)
            continue
        v = feature_vif(sub, feats)
        qual = {f: (bool(v.get(f, np.nan) < VIF_SEVERE)) for f in feats}
        for f in feats:
            if qual.get(f) != full_qual.get(f):
                flips[f] += 1
        if frozenset(f for f, ok in qual.items() if ok) != full_set:
            set_changes += 1

    folds = n  # one fold per dyad
    per_feature = {
        f: {
            "qualifies_full": bool(full_qual[f]),
            "loo_flips": flips[f],
            "stability_pct": round(100.0 * (folds - flips[f]) / max(folds, 1), 1),
        }
        for f in feats
    }
    return {
        "n_dyads": n,
        "folds": folds,
        "full_vif": {f: (None if pd.isna(full_vif.get(f, np.nan)) else float(full_vif.get(f)))
                     for f in feats},
        "full_qualifying_set": sorted(full_set),
        "per_feature": per_feature,
        "set_changes": set_changes,
        "overall_stability_pct": round(100.0 * (folds - set_changes) / max(folds, 1), 1),
    }


# ═══════════════════════════════════════════════════════════════════════════
# Output
# ═══════════════════════════════════════════════════════════════════════════
def write_bakeoff_csv(results: Dict[str, Dict]) -> Path:
    """Wide matrix: rows = (VIF per feature) + (pearson_rho per pair);
    columns = datasets. A META block records per-column mode + thresholds."""
    datasets = list(results.keys())
    rows = []

    # META: data mode per column
    rows.append({
        "metric": "META_mode", "item": "data_mode",
        **{d: results[d]["mode"] for d in datasets},
    })
    rows.append({
        "metric": "META_n_dyads", "item": "n_independent_dyads",
        **{d: results[d]["n_dyads"] for d in datasets},
    })
    rows.append({
        "metric": "META_threshold", "item": "VIF_severe",
        **{d: VIF_SEVERE for d in datasets},
    })

    # VIF rows
    all_feats = []
    for d in datasets:
        for f in results[d]["feats"]:
            if f not in all_feats:
                all_feats.append(f)
    for f in all_feats:
        row = {"metric": "VIF", "item": f}
        for d in datasets:
            v = results[d]["vif"].get(f, np.nan)
            row[d] = (None if (v is None or (isinstance(v, float) and np.isnan(v))) else round(float(v), 4))
        rows.append(row)

    # Pearson-rho rows (upper triangle pairs)
    for i in range(len(all_feats)):
        for j in range(i + 1, len(all_feats)):
            fa, fb = all_feats[i], all_feats[j]
            row = {"metric": "pearson_rho", "item": f"{fa}~{fb}"}
            for d in datasets:
                rho = results[d]["rho"].get((fa, fb), np.nan)
                row[d] = (None if (isinstance(rho, float) and np.isnan(rho)) else round(float(rho), 4))
            rows.append(row)

    out = pd.DataFrame(rows, columns=["metric", "item"] + datasets)
    path = OUT_DIR / "fdr_family_bakeoff.csv"
    out.to_csv(path, index=False)
    return path


def write_loo_csv(results: Dict[str, Dict]) -> Path:
    rows = []
    for d, r in results.items():
        if not r.get("loo"):
            continue
        for f, info in r["loo"]["per_feature"].items():
            rows.append({
                "dataset": d,
                "mode": r["mode"],
                "n_dyads": r["loo"]["n_dyads"],
                "feature": f,
                "in_primary_fdr_family": f in FDR_PRIMARY,
                "qualifies_full": info["qualifies_full"],
                "loo_flips": info["loo_flips"],
                "stability_pct": info["stability_pct"],
            })
    out = pd.DataFrame(rows, columns=[
        "dataset", "mode", "n_dyads", "feature",
        "in_primary_fdr_family", "qualifies_full", "loo_flips", "stability_pct",
    ])
    path = OUT_DIR / "fdr_family_loo_stability.csv"
    out.to_csv(path, index=False)
    return path


# ═══════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════
def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    t0 = datetime.now()

    # ── 1. Load each dataset (real where available, else synthetic smoke) ──────
    datasets: Dict[str, Tuple[pd.DataFrame, List[str], str]] = {}
    if LEROIQUE_CSV.exists():
        datasets["lerique"] = load_lerique_real()
    else:
        print("[WARN] Lerique real feature table missing — falling back to synthetic.")

    for name in ("gordon", "andersen"):
        try:
            df, keys, mode = generate_synthetic_dataset(name, SYNTH_N[name], SYNTH_SEED[name])
            datasets[name] = (df, keys, mode)
        except Exception as exc:  # pragma: no cover - defensive
            print(f"[ERROR] synthetic {name} failed: {exc}")

    results: Dict[str, Dict] = {}
    for name, (df, dyad_keys, mode) in datasets.items():
        feats = [c for c in FDR_CANDIDATES if c in df.columns]
        rho_df = pearson_rho(df, feats)
        vif = feature_vif(df, feats)
        rho_map = {}
        for i in range(len(feats)):
            for j in range(i + 1, len(feats)):
                rho_map[(feats[i], feats[j])] = float(rho_df.iloc[i, j])

        loo = None
        n_dyads = len(set(dyad_keys))
        if n_dyads >= LOO_MIN_N:
            loo = loo_stability(df, dyad_keys, feats)

        results[name] = {
            "mode": mode,
            "n_dyads": n_dyads,
            "feats": feats,
            "rho": rho_map,
            "vif": {f: (None if pd.isna(vif.get(f, np.nan)) else float(vif.get(f))) for f in feats},
            "loo": loo,
        }
        print(f"[OK] {name}: mode={mode} n_dyads={n_dyads} features={len(feats)}")

    # ── 2. Write outputs ──────────────────────────────────────────────────────
    bake_path = write_bakeoff_csv(results)
    loo_path = write_loo_csv(results)

    # ── 3. Console summary ───────────────────────────────────────────────────
    print("\n" + "=" * 78)
    print("B4 FDR-FAMILY BAKE-OFF  (Pearson rho + VIF; LOO stability for N>=23)")
    print("=" * 78)
    print(f"VIF severe threshold = {VIF_SEVERE}  |  VIF concern = {VIF_CONCERN}")
    print("\n-- VIF per feature (lower = more independent) --")
    for name, r in results.items():
        print(f"\n[{name}] mode={r['mode']} n_dyads={r['n_dyads']}")
        for f in r["feats"]:
            v = r["vif"][f]
            vs = "NaN" if v is None else f"{v:.3f}"
            flag = ""
            if v is not None:
                if v >= VIF_SEVERE:
                    flag = "  <-- SEVERE"
                elif v >= VIF_CONCERN:
                    flag = "  <-- concern"
            prim = " [primary-FDR]" if f in FDR_PRIMARY else (" [reference]" if f in FDR_REFERENCE else "")
            print(f"    {f:<24} VIF={vs:<8}{flag}{prim}")

    print("\n-- Top collinear feature pairs (|Pearson rho|) --")
    for name, r in results.items():
        pairs = sorted(r["rho"].items(), key=lambda kv: abs(kv[1]), reverse=True)[:3]
        top = "; ".join(f"{a}~{b}={rho:.2f}" for (a, b), rho in pairs)
        print(f"  [{name}] {top}")

    print("\n-- LOO stability (leave-one-dyad-out, VIF-qualifying-set) --")
    for name, r in results.items():
        loo = r.get("loo")
        if not loo:
            print(f"  [{name}] N={r['n_dyads']} < {LOO_MIN_N}: LOO skipped")
            continue
        print(f"  [{name}] N={loo['n_dyads']}  overall stability = "
              f"{loo['overall_stability_pct']:.1f}%  "
              f"(set changed in {loo['set_changes']}/{loo['folds']} folds)")
        flips = {f: info["loo_flips"] for f, info in loo["per_feature"].items()}
        worst = sorted(flips.items(), key=lambda kv: kv[1], reverse=True)[:3]
        print("      most-unstable features: " +
              "; ".join(f"{f}={c} flips" for f, c in worst))

    print("\n" + "=" * 78)
    print(f"Wrote: {bake_path}")
    print(f"Wrote: {loo_path}")
    if any(r["mode"] != "real" for r in results.values()):
        print("\nNOTE: Gordon/Andersen columns are SYNTHETIC pipeline smoke "
              "(B1 data not downloaded; OSF 'No license'). They validate the "
              "script/pipeline, NOT the FDR-family decision. Real-data evidence "
              "for those datasets lives in the pre-existing artifacts/vif/*.json.")
    print(f"\nElapsed: {datetime.now() - t0}")


if __name__ == "__main__":
    main()
